# global parameters
project_name: 'Data-Juicer-recipes-alpaca-cot-en'
dataset_path: '/home/zhx/competition_kit/data/raw_data/raw_data_en.jsonl'  # path to your dataset directory or file
export_path: '/home/zhx/competition_kit/data/refined_data/refined_data_en.jsonl'
ds_cache_dir: '/home/zhx/competition_kit/.cache/huggingface/datasets'  
np: 50  # number of subprocess to process your dataset
open_tracer: true

# process schedule
# a list of several process operators with their arguments
process:
  - document_deduplicator: # 104636705
      lowercase: true 
      ignore_non_character: true
      
  - alphanumeric_filter: # 104636381
      tokenization: false
      min_ratio: 0.1
  - character_repetition_filter: # 104630030
      rep_len: 10
      max_ratio: 0.6
  - flagged_words_filter: # 104576967
      lang: en
      tokenization: true
      max_ratio: 0.007 
  - perplexity_filter:
      lang: en
      max_ppl: 1800  # <3sigma (16516)
  - maximum_line_length_filter: # 104575811
      min_len: 50
  - text_length_filter: # 104573711
      min_len: 50

  - document_simhash_deduplicator:  # 72855345
      tokenization: space
      window_size: 3
      lowercase: true
      ignore_pattern: '\p{P}'
      num_blocks: 9
      hamming_distance: 7

  - document_minhash_deduplicator:                          # deduplicate text samples using MinHash-LSH method
      tokenization: space                                     # tokenization method for text. One of [space, punctuation, character]
      window_size: 3                                          # window size of shingling
      num_permutations: 128                                   # number of permutations in minhash computing
      jaccard_threshold: 0.7                                  # the min jaccard similarity threshold in near-duplicate detection. When the jaccard similarity of two sample texts is >= this threshold, they are regarded as similar samples and this op will only keep one of them after deduplication
#      num_bands: None                                         # number of bands in LSH. Default it's None, and it will be determined by an optimal params computation algorithm by minimize the weighted sum of probs of False Positives and False Negatives
#      num_rows_per_band: None                                 # number of rows in each band in LSH. Default it's None, and it will be determined by an optimal params computation algorithm
      lowercase: true                                         # whether to convert text to lower case
      ignore_pattern: '\p{P}'                                 # whether to ignore sub-strings with specific pattern when computing simhash.
